---
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: NemoGuardrails
metadata:
  name: lemonade
spec:
  nemoConfigs:
    - name: lemonade-stand
      default: true
      configMaps:
        - lemonade-config
  env:
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: lemonade-secret
          key: api-key