---
apiVersion: v1
kind: Secret
metadata:
  name: lemonade-secret
type: Opaque
stringData:
  api-base: "${LLM_API_BASE}"
  model-name: "${LLM_MODEL_NAME}"
  api-key: "${LLM_API_KEY}"
  injection-guard-api-base: "${INJECTION_GUARD_API_BASE}"
  injection-guard-model-name: "${INJECTION_GUARD_MODEL_NAME}"
  injection-guard-api-key: "${INJECTION_GUARD_API_KEY}"
  hap-guard-api-base: "${HAP_GUARD_API_BASE}"
  hap-guard-model-name: "${HAP_GUARD_MODEL_NAME}"
  hap-guard-api-key: "${HAP_GUARD_API_KEY}"